# Generated by Django 5.1.7 on 2025-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('released', models.DateField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('rawg_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
