# Generated by Django 5.2 on 2025-04-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customuser_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='description',
            new_name='bio',
        ),
    ]
