# Generated by Django 5.1.7 on 2025-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_genre_platform_store_alter_game_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='store',
            name='image_background',
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='store.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='store.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(to='store.store'),
        ),
    ]
