# Generated by Django 5.2 on 2025-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customuser_avatar_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
