# Generated by Django 5.2 on 2025-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
