# Generated by Django 5.2 on 2025-04-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_game_price_kzt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_kzt',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
